SOP_IAA/Models/ContratoViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SOP_IAA_DAL;
using System.Web.Mvc;

namespace SOP_IAA.Models
{
    public class ContratoViewModels
    {
       
        public int id { get; set; }
        public int idContratista { get; set; }
        public string licitacion { get; set; }
        public short lineaContrato { get; set; }
        public short idZona { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public short plazo { get; set; }
        public string lugar { get; set; }
        public short idFondo { get; set; }

        public Contrato contrato { get; set; }

    }
}

SOP_IAA/Controllers/BoletaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SOP_IAA_DAL;

namespace SOP_IAA.Controllers
{
    public partial class BoletaController : Controller
    {
        private Proyecto_IAAEntities db = new Proyecto_IAAEntities();

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SOP_IAA/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SOP_IAA_DAL;

namespace SOP_IAA.Controllers
{
    public partial class ContratoController : Controller
    {
        private Proyecto_IAAEntities db = new Proyecto_IAAEntities();

        // GET: Contrato
        public ActionResult Index()
        {
            var contrato = db.Contrato.Include(c => c.contratista).Include(c => c.fondo).Include(c => c.zona);
            return View(contrato.ToList());
        }

        // GET: Contrato/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrato contrato = db.Contrato.Find(id);
            if (contrato == null)
            {
                return HttpNotFound();
            }
            return View(contrato);
        }
        
        // GET: Contrato/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrato contrato = db.Contrato.Find(id);
            if (contrato == null)
            {
                return HttpNotFound();
            }
            return View(contrato);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SOP_IAA/Controllers/ContratoItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SOP_IAA_DAL;

namespace SOP_IAA.Controllers
{
    public partial class ContratoItemController : Controller
    {
        private Proyecto_IAAEntities db = new Proyecto_IAAEntities();


        /*// GET: ContratoItem
        public ActionResult Index()
        {
            var contratoItem = db.contratoItem.Include(c => c.Contrato).Include(c => c.item);
            return View(contratoItem.ToList());
        }

        // GET: ContratoItem/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contratoItem contratoItem = db.contratoItem.Find(id);
            if (contratoItem == null)
            {
                return HttpNotFound();
            }
            return View(contratoItem);
        }

        // GET: ContratoItem/Create
        public ActionResult Create()
        {
            ViewBag.idContrato = new SelectList(db.Contrato, "id", "licitacion");
            ViewBag.idItem = new SelectList(db.item, "id", "codigoItem");
            return View();
        }

        // POST: ContratoItem/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idContrato,idItem,precioUnitario")] contratoItem contratoItem)
        {
            if (ModelState.IsValid)
            {
                db.contratoItem.Add(contratoItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idContrato = new SelectList(db.Contrato, "id", "licitacion", contratoItem.idContrato);
            ViewBag.idItem = new SelectList(db.item, "id", "codigoItem", contratoItem.idItem);
            return View(contratoItem);
        }

        // GET: ContratoItem/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contratoItem contratoItem = db.contratoItem.Find(id);
            if (contratoItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.idContrato = new SelectList(db.Contrato, "id", "licitacion", contratoItem.idContrato);
            ViewBag.idItem = new SelectList(db.item, "id", "codigoItem", contratoItem.idItem);
            return View(contratoItem);
        }

        // POST: ContratoItem/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idContrato,idItem,precioUnitario")] contratoItem contratoItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contratoItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idContrato = new SelectList(db.Contrato, "id", "licitacion", contratoItem.idContrato);
            ViewBag.idItem = new SelectList(db.item, "id", "codigoItem", contratoItem.idItem);
            return View(contratoItem);
        }

        // GET: ContratoItem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contratoItem contratoItem = db.contratoItem.Find(id);
            if (contratoItem == null)
            {
                return HttpNotFound();
            }
            return View(contratoItem);
        }

        // POST: ContratoItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            contratoItem contratoItem = db.contratoItem.Find(id);
            db.contratoItem.Remove(contratoItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }*/

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SOP_IAA/Controllers/ReportesController.cs
using SOP_IAA_DAL;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SOP_IAA.Controllers
{
    public class ReportesController : Controller
    {
        private Proyecto_IAAEntities db = new Proyecto_IAAEntities();

        // GET: Items del contrato
        public ActionResult Index(int? idContrato)
        {
            if ((idContrato == null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrato contrato = db.Contrato.Find(idContrato);
            return View(contrato);
        }

        //GET: 
        public ActionResult Reports(int? id)
        {
            if ((id == null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contratoItem contratoItem = db.contratoItem.Find(id);
            return View(contratoItem);
        }

        public ActionResult Export(int? id)
        {
            if ((id == null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            contratoItem contraroItem = db.contratoItem.Find(id);
            // Load Excel application
            Microsoft.Office.Interop.Excel.Application excel = new Microsoft.Office.Interop.Excel.Application();

            // Create empty workbook
            excel.Workbooks.Add();

            // Create Worksheet from active sheet
            Microsoft.Office.Interop.Excel._Worksheet workSheet = excel.ActiveSheet;

            // I created Application and Worksheet objects before try/catch,
            // so that i can close them in finnaly block.
            // It's IMPORTANT to release these COM objects!!
            try
            {
                // ------------------------------------------------
                // Creation of header cells
                // ------------------------------------------------
                workSheet.Cells[1, "A"] = "Número de boleta";
                workSheet.Cells[1, "B"] = "Fecha";
                workSheet.Cells[1, "C"] = "Ruta";
                workSheet.Cells[1, "D"] = "Sección de control";
                workSheet.Cells[1, "E"] = "Estacionamiento inicial";
                workSheet.Cells[1, "F"] = "Estacionamiento final";
                workSheet.Cells[1, "G"] = "Cantidad";
                workSheet.Cells[1, "H"] = "Nombre";
                workSheet.Cells[1, "I"] = "Proyecto/Estructura";

                // ------------------------------------------------
                // Populate sheet with some real data from "cars" list
                // ------------------------------------------------
                int row = 2; // start row (in row 1 are header cells)
                foreach (var item in contraroItem.boletaItem)
                {
                    workSheet.Cells[row, "A"] = item.boleta.numeroBoleta;
                    workSheet.Cells[row, "B"] = item.boleta.fecha;
                    workSheet.Cells[row, "C"] = item.boleta.ruta.nombre;
                    workSheet.Cells[row, "D"] = item.boleta.seccionControl;
                    workSheet.Cells[row, "E"] = item.boleta.estacionamientoInicial;
                    workSheet.Cells[row, "F"] = item.boleta.estacionamientoFinal;
                    workSheet.Cells[row, "G"] = item.cantidad;
                    workSheet.Cells[row, "H"] = item.boleta.inspector.persona.nombre + " " 
                        + item.boleta.inspector.persona.apellido1 + " " 
                        + item.boleta.inspector.persona.apellido2;
                    workSheet.Cells[row, "I"] = item.boleta.proyecto_estructura.descripcion;

                    row++;
                }

                // Apply some predefined styles for data to look nicely :)
                workSheet.Range["A1"].AutoFormat(Microsoft.Office.Interop.Excel.XlRangeAutoFormat.xlRangeAutoFormatClassic1);

                // Define filename
                string fileName = string.Format(@"{0}\ExcelData.xlsx", Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory));

                // Save this data as a file
                workSheet.SaveAs(fileName);

                // Display SUCCESS message
                //MessageBox.Show(string.Format("The file '{0}' is saved successfully!", fileName));
            }
            catch (Exception exception)
            {
                //MessageBox.Show("Exception",
                  //  "There was a PROBLEM saving Excel file!\n" + exception.Message,
                   // MessageBoxButtons.OK, MessageBoxIcon.Error);

            }
            finally
            {
                // Quit Excel application
                excel.Quit();

                // Release COM objects (very important!)
                if (excel != null)
                    System.Runtime.InteropServices.Marshal.ReleaseComObject(excel);

                if (workSheet != null)
                    System.Runtime.InteropServices.Marshal.ReleaseComObject(workSheet);

                // Empty variables
                excel = null;
                workSheet = null;

                // Force garbage collector cleaning
                GC.Collect();
            }
            return RedirectToAction("Reports", new { id = contraroItem.id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SOP_IAA/Views/Contrato/Delete.cshtml
@model SOP_IAA_DAL.Contrato

@{
    ViewBag.Title = "Eliminar Contrato";
}

<h2></h2>

<h3>
    @SOP_IAA_Utilerias.Utilerias.ValorRecurso(SOP_IAA_Utilerias.Utilerias.ArchivoRecurso.UtilRecursos, "MSJ_CONFIRM_ELIMINAR_CONTRATO")
</h3>
<div>
    <h4> </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.licitacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.licitacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lineaContrato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lineaContrato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.plazo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.plazo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lugar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lugar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contratista.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contratista.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fondo.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fondo.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zona.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zona.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar Contrato" class="btn btn-danger"/> |
            @Html.ActionLink("Atrás", "MiContrato", new { id = Model.id })
        </div>
    }
</div>

SOP_IAA/Views/Contrato/Index.cshtml
@model IEnumerable<SOP_IAA_DAL.Contrato>

@{
    ViewBag.Title = "Lista Contratos";
}

<h2> </h2>

<p>
    @Html.ActionLink("Nuevo Contrato", "Create", null, new { @class = "btn btn-primary", @style = "width:150px" })
    @*@Html.ActionLink("Excel", "exportarInformeDescriptivoItem", "Reportes", new { id = 1 }, new { @class = "btn btn-primary", @style = "width:150px" })*@
</p>
<br />


<div class="panel panel-default">
    <div class="panel-heading">
        Contratos de IAA
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table id="tbContratos" class="display table table-responsive">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.licitacion)
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.lineaContrato)
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.fechaInicio)
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.plazo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.lugar)
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.contratista.nombre)
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.fondo.nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.zona.nombre)
                        </th>*@
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.licitacion)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.lineaContrato)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.fechaInicio)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.plazo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.lugar)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.contratista.nombre)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.fondo.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.zona.nombre)
                        </td>*@
                        <td>
                            @Html.ActionLink("Ir al Contrato", "MiContrato", new { id = item.id })
                            @*@Html.ActionLink("Editar", "Edit", new { id=item.id }) |
                        @Html.ActionLink("Programas", "Programs", new { id = item.id }) |
                        @Html.ActionLink("Detalles", "Details", new { id=item.id }) |
                        @Html.ActionLink("Eliminar", "Delete", new { id=item.id })*@
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>

@section Scripts{
    <link rel="stylesheet" href="~/Content/jquery.dataTables.min.css" />
    <script src="~/Scripts/plugins/dataTables/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tbContratos').dataTable( {
                "language": {
                    "url": "/Scripts/plugins/dataTables/Spanish.txt"
                }
            });
        })
    </script>
}

SOP_IAA/Views/Contrato/MiContrato.cshtml
@model SOP_IAA_DAL.Contrato

@{
    ViewBag.Title = "Contratación" + @Model.licitacion;
    ViewBag.contratacion = @Model.licitacion;

    // Se especifica el formato de Costa Rica
    System.Globalization.CultureInfo cultureCR = System.Globalization.CultureInfo.CreateSpecificCulture("es-CR");

    // Se cambia la Cultura Actual por la de Costa Rica.
    System.Threading.Thread.CurrentThread.CurrentCulture = cultureCR;
}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Contratación @Model.licitacion</h2>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <!-- Panel de información del contrato -->
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            @*<div class="panel-heading">
                <div class="row">
                    <div class="text-center">
                        <div class="fa fa-info-circle fa-5x"> </div>
                    </div>
                </div>
            </div>*@
            <a href="@Url.Action("Details", "Contrato", new { id = Model.id })">
                <div class="panel-footer">
                    <span class="pull-left">Detalles del Contrato</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <!-- Panel de items del contrato -->
    <div class="col-lg-3 col-md-6">
        @*<div class="panel panel-green" style="border-color:#5cb85c">*@
        <div class="panel panel-primary">
            @*<div class="panel-heading">
                    <div class="row">
                        <div class="text-center">
                            <div class="fa fa-tasks fa-5x"> </div>
                        </div>
                    </div>
                </div>*@
            <a href="@Url.Action("Index", "ContratoItem", new { idContrato = Model.id })">
                <div class="panel-footer">
                    <span class="pull-left">Items del Contrato</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <!-- Panel de reajustes -->
    <div class="col-lg-3 col-md-6">
        @*<div class="panel panel-yellow" style="border-color:#f0ad4e">*@
        <div class="panel panel-primary">
            <a href="@Url.Action("index", "ItemReajuste", new { idContrato = Model.id })">
                <div class="panel-footer">
                    <span class="pull-left">Reajustes</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <!-- Panel de boletas del contrato -->
    <div class="col-lg-3 col-md-6">
        @*<div class="panel panel-yellow" style="border-color:#f0ad4e">*@
        <div class="panel panel-primary">
            @*<div class="panel-heading">
                    <div class="row">
                        <div class="text-center">
                            <div class="fa fa-file-text fa-5x"> </div>
                        </div>
                    </div>
                </div>*@
            <a href="@Url.Action("index", "Boleta", new { idContrato = Model.id })">
                <div class="panel-footer">
                    <span class="pull-left">Boletas</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <!-- Panel de plan de inversión del contrato -->
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <a href="@Url.Action("Index", "PlanInversion", new { idContrato = Model.id })">
                <div class="panel-footer">
                    <span class="pull-left">Plan de Inversión</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <!-- Panel de control de inversión del contrato -->
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <a href="@Url.Action("Index", "ControlInversion", new { idContrato = Model.id })">
                <div class="panel-footer">
                    <span class="pull-left">Avance Items</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <!-- Panel de Ordenes de modificación del contrato -->
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <a href="@Url.Action("Index", "OrdenModificacion", new { idContrato = Model.id })">
                <div class="panel-footer">
                    <span class="pull-left">Órdenes de Modificación</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <!-- Panel de Reportes del contrato -->
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <a href="@Url.Action("index", "Reportes", new { idContrato = Model.id })">
                <div class="panel-footer">
                    <span class="pull-left">Reportes</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Datos Generales
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table id="tbDetallesGenerales" class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.licitacion)</th>
                                <td>@Html.DisplayFor(model => model.licitacion)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.lineaContrato)</th>
                                <td>@Html.DisplayFor(model => model.lineaContrato)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.fechaInicio)</th>
                                <td>@Model.fechaInicio.ToLongDateString()</td>
                            </tr>
                            @{
                                var fechaInicio = Model.fechaInicio;
                                var plazo = Model.plazo;
                                foreach (var om in Model.ordenModificacion)
                                {
                                    plazo += om.AumentoPlazo;
                                }
                                var fechaFin = fechaInicio.AddDays(plazo);
                            }
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.plazo)</th>
                                <td>@plazo</td>
                            </tr>
                            <tr>
                                <th>Fecha de Finalización</th>
                                <td>@fechaFin.ToLongDateString()</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.lugar)</th>
                                <td>@Html.DisplayFor(model => model.lugar)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.contratista.nombre)</th>
                                <td>@Html.DisplayFor(model => model.contratista.nombre)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.fondo.nombre)</th>
                                <td>@Html.DisplayFor(model => model.fondo.nombre)</td>
                            </tr>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.zona.nombre)</th>
                                <td>@Html.DisplayFor(model => model.zona.nombre)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
    <br />
</div>

<div class="row">
    <!-- Panel Danger -->
    <div class="col-sm-12">
        <div class="col-lg-offset-0">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    Opciones del Contrato
                </div>
                <div class="panel-body">
                    <div class="text-center">
                        @Html.ActionLink("Editar Contrato", "Edit", new { id = Model.id }, new { @class = "btn btn-warning", @style = "width:150px" }) |
                        @Html.ActionLink("Eliminar Contrato", "Delete", new { id = Model.id }, new { @class = "btn btn-danger", @style = "width:150px" })
                    </div>

                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    
    <script src="~/Content/admin_bootstrap.css"></script>
    
}